### PR TITLE
Fairly simple update

### PR DESCRIPTION
**Pull request by mdsumner**
Hey, I happened to update this - thanks!

If you like to merge this pull request, perhaps 

* tag your repo before hand so it turns up as a release? 
* Update the Github page description line  on your repo
* remove original /figures/ folder? (the github readme form puts them in README_files/)
* And then tag and release after you merge. 

I like the idea of having clear snapshots, even if only you and me ever care!  This is an interesting little data set. 

Some minor changes made, to make the text less *dated*, also to note the date that the archive goes back to rather than "about a year". 

I also used the modern `usethis` readme.rmd format for github. 

Nice work!

### CODE REVIEW

**Comment by jimjam-slam** [comment]
Thanks for the update and the code cleanup, Michael! Yeah, it's an interesting dataset 😄

FYI, I'm about to add an issue for pulling dates out of the entries that are referred to without their name (eg. "Campaign Special" rather than "Tuesday 14 April"). They weren't there before, but the entries now seem to have post timestamps that might be more reliable than titles (unless episodes get posted late). if I get a moment on the weekend, I'll look at using that instead 🙂

**Comment by mdsumner** [comment]
cool, I looked at that too but it's a bit hard for me - it's cool to see this scraping logic, I'm very dim about that topic!

I wonder if this could be applied to other ABC sites, like qanda? (A rainy day project)

**Comment by mdsumner** [comment]
Oh dang, I only just realized the data does only go back a year - so I should have merged the old and new CSVs. I'll have another look

**Comment by jimjam-slam** [comment]
Mmm, no worries! I'll try to pop it open later tonight for another look if you don't get there (I tried to make a few quick changes and ended up having to force push an amend commit to walk it back to yours, sorry!). 

Perhaps applying this analysis to Q&A or other shows by forking and modifying the notebook would make a good workshop exercise?

**Comment by jimjam-slam** [comment]
https://www.abc.net.au/tv/programs/drum/ looks like it could actually be a better place to scrape from: it goes all the way back to 2013! No guest data other than the descriptions though 😕

**Pull request merged**
